version: "2"
services:
  master:
    image: bitnami/jenkins-master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m -Djenkins.install.runSetupWizard=false
    volumes:
    - jenkins-master:/var/jenkins_home

  worker1:
    image: bitnami/jenkins-slave
    environment:
      JAVA_OPTS: "-Xmx2048m -Djenkins.install.runSetupWizard=false"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker1"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "jenkins"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker1:/var/jenkins_home/worker

  worker2:
    image: bitnami/jenkins-slave
    environment:
      JAVA_OPTS: "-Xmx2048m -Djenkins.install.runSetupWizard=false"
      JENKINS_MASTER: "http://master:8080
      JENKINS_NAME: "worker2"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "jenkins"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker2:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-worker1:
  jenkins-worker2:
  jenkins-worker2:
